### ISSUE TITLE
`etcal` does not work on arrays of floats

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#102]
The function `etcal` converts from an ephemeris epoch measured in seconds past the epoch of J2000 to a calendar string format using a formal calendar. Here are the inputs and returns:
```
    Inputs:
      float  et     = Ephemeris time measured in seconds past J2000.
    
    Returns:
      string string = A standard calendar representation of et.
```

The current problem is that the intended functionality is that output `cal` can be a string or an array of strings depending on the `et` input. If `et` is a single float, `cal` is a single string. If `et` is an array of floats, then `cal` should be an array of strings. Currently, this unit test:

```
import cspyce as cs
import numpy as np


et = np.arange(0.0, 20.0)
cal = cs.etcal(et[0])
assert cal == "2000 JAN 01 12:00:00.000"
calArr = cs.etcal(et)
assert calArr[0] == cal
assert calArr[1] == "2000 JAN 01 12:00:01.000"
assert calArr[-1] == "2000 JAN 01 12:00:19.000"
```

is failing and giving this error:

```
TypeError: in method 'etcal', argument 1 of type 'SpiceDouble'
```

`cspyce.etcal` works on single inputs, but not on arrays. Creating a loop within this unit test can achieve the desired result, but the functionality should not rely on this.

**Comment by fyellin** [comment]
Just chatted with Mark.

For now, cspyce doesn't support arrays of strings.  If etcal were a vector operation, it would require returning an array (or list or tuple or something) of strings.  

This decision may be revisited in the future.

**Comment by rfrenchseti** [comment]
Note that the actual CSPICE `etcal` function does not support an array of ETs as an input. It SpiceyPy supports this, it is added functionality.

**Comment by esimpsons3ti** [comment]
I see that now. Since this doesn't reflect intended functionality and the function otherwise works correctly, I will close this issue.
