### ISSUE TITLE
Support pathlib filespecs

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/pds-cspyce#104]
As Python's `pathlib` gains popularity, it would be nice if `cspyce` accepted `pathlib` objects where filenames are expected.

See `SpiceyPy`: https://github.com/AndrewAnnex/SpiceyPy/pull/436

**Comment by fyellin** [comment]
Pull #118 does a first pass at this. It lets Leopoldo and furnish use paths. 

Give me a list of methods that take file arguments and I can finish this.

**Comment by fyellin** [comment]
Just looked at the SpiceyPy list of functions.  Seems we have a lot more functions that take filename arguments.

Question 1:
What do we want to do with dashfn.  It's the only function that *returns* a filename.  Do we want it returning a string, a byte string, or a Path?

Question 2:
Several functions take a "filename" and an "internal filename".  I'm presuming the former should be a Path and the latter shouldn't.  See ckopn()

Question 3:
Here is the list of functions that have what I think is a filename argument. 
ckcov, ckobj, furnsh, ldpool, pckcov, pckfrm, spkcov, spkobj, unload,
cklpf, ckopn, dasonw, dasopr, dasopw, dlaopn, dskobj, dskopn, dskfnm, 
eklef, ekopn, ekopr, ekopw, getfat, kinfo, pcklof, pckopn, spklef, spkopa, spkopn

There is also the function stcl01.  I can find no documentation on it at the NAIF web site.  Hard to know what this is.

This list was generated by going throw cspyce0.i and cspyce0_part2.i and looking for the word "file" with the corresponding argument being a CONST_STRING.  

Are these all actual files?  Are there others that i'm missing?

In any case, input can be changed by just replacing CONST_STRING with CONST_FILENAME, and magically the right thing is supposed to happen.

**Comment by fyellin** [comment]
@matthewtiscareno 
Adding Matt to the conversation, since we need input from a toolkit user.

**Comment by rfrenchseti** [comment]
1) I would say when returning a filename, just return a string. That's the most universal response.
2) An "internal filename" appears to just be a unique name or tag. It doesn't have to be a real file path, and thus shouldn't be a Path. I would return a string.
3) stcl01 is part of the star catalog support: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/stcl01.html
I don't know why there isn't a C webpage for it, since it's clearly in the CSPICE library.
All of the functions you mentioned appear to take real filenames, except I can't find "dskfnm".

**Comment by rfrenchseti** [comment]
This issue is closed so I don’t think I we need further input unless you disagree with the decisions made above.

**Comment by matthewtiscareno** [comment]
Okay, reading through it, it's probably fine.  @rfrenchseti, you're as much of a SPICE user as I am, aren't you?  A lot of this stuff is digging into innards of SPICE that I've never used, though I have enough general familiarity to come up to speed as needed.

**Comment by fyellin** [comment]
Anything you need from me on this?

**Comment by rfrenchseti** [comment]
> Anything you need from me on this?

No
