### ISSUE TITLE
`oscelt` is giving incorrect results

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#115]
The function `oscelt` determines the set of osculating conic orbital elements that corresponds
    to the state (position, velocity) of a body at some epoch. Here are the `cspyce` inputs and returns:

```
    Inputs:
      float[6] state = State of body at epoch of elements.
      float    et    = Epoch of elements.
      float    mu    = Gravitational parameter (GM) of primary body.
    
    Returns:
      float[8] elts  = Equivalent conic elements.
```
These values agree with their CSPICE counterpart.

Currently this function is failing due to a mismatch of values. Here is the unit test:

```
import cspyce as cs
import numpy.testing as npt

from gettestkernels import CoreKernels
    
cs.furnsh(CoreKernels.testMetaKernel)
et = cs.str2et("Dec 25, 2007")
state, ltime = cs.spkezr("Moon", et, "J2000", "LT+S", "EARTH")
mass_earth = cs.bodvrd("EARTH", "GM")
elts = cs.oscelt(state, et, mass_earth[0])
expected = [
    3.65914105273643566761e05,
    4.23931145731340453494e05,
    4.87177926278510253777e-01,
    6.18584206992959551030e00,
    1.88544634402406319218e00,
    1.86769787246217056236e04,
    2.51812865183709204197e08,
    1.00000000000000000000e00,
]
npt.assert_array_almost_equal(list(elts), expected, decimal=4)
```

The current output values are:

```
[360975
0.0781035
0.487178
6.18584
1.28679
0.553313
2.51813e+08
398600]
```

**Comment by fyellin** [comment]
This is a bug in SpiceyPy that I have just reported.  

https://github.com/AndrewAnnex/SpiceyPy/issues/468

The values we have are correct.  

    expected = [
        3.60975119168868346605e+05,
        7.81035176779166367966e-02,
        4.87177926278510309288e-01,
        6.18584206992959551030e+00,
        1.28678805411666807856e+00,
        5.53312778515375192079e-01,
        2.51812865183709204197e+08,
        3.98600435436095925979e+05
     ]

**Comment by fyellin** [comment]
Giving this back to Emilie.  Code is correct.  Test needs to be fixed.
