### ISSUE TITLE
`tkfram` is giving inverse results

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#130]
The function `tkfram` finds the position rotation matrix from a Text Kernel (TK) frame with the specified frame class ID to its base frame. Here are the inputs and returns:

```
    Inputs:
      int        frcode = Frame class ID of a TK frame.
    
    Returns:
      float[3,3] rot    = Rotation matrix from TK frame to frame `frame'.
      int        frame  = Frame ID of the base reference.
```

This unit test is failing:
```
import cspyce as cs
import numpy as np
import numpy.testing as npt

from gettestkernels import (
    CoreKernels,
    CassiniKernels
)


cs.furnsh(CoreKernels.testMetaKernel)
cs.furnsh(CassiniKernels.cassFk)
rotation, nextFrame = cs.tkfram(-82001)
expected = np.array(
    [
        [6.12323400e-17, 0.00000000e00, -1.00000000e00],
        [0.00000000e00, 1.00000000e00, -0.00000000e00],
        [1.00000000e00, 0.00000000e00, 6.12323400e-17],
    ]
)
npt.assert_array_almost_equal(rotation, expected)
assert nextFrame == -82000
```

The `rotation` variable is being output as inverse to the expected variable:

```
[[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00 -0.000000e+00  6.123234e-17]]
```

Is our code extracting the rotation matrix incorrectly? Or is this version correct?

**Comment by fyellin** [comment]
I'm going to need the help of an astronomer here.  I don't know which is correct, the result we're returning on the transposition.  The documentation indicates that there are two vectors V' and V such that V' = matrix * V.  But I'm not sure what V' and V are.

**Comment by fyellin** [comment]
This appears to be a bug in SpiceyPy, and we are returning the correct matrix. 

https://github.com/AndrewAnnex/SpiceyPy/issues/473

I'm going to give Andrew a chance to respond.

**Comment by fyellin** [comment]
Our result is correct. Please fix the test by either by (1) changing `expected = np.array(.....)` to `expected = np.array(....).T` or else just transposing the array yourself, which involves moving two minus signs.
