### ISSUE TITLE
Releases or tagged versions?

### ISSUE THREAD

**Issue by gpdf** [SETI/pds-cspyce#14]
The current README.md says that it's "Version 2.0" but there are no releases on GitHub, and no non-release tags.  Do you have some other mechanism for declaring releases?

We'd be interested in evaluating using this package vis-a-vis `SpiceyPy` but our software management guidelines require configuration management.  We could do that in a fork, but I'm sure you know more than we could about your release cycle.  :)

**Comment by astrocfi** [comment]
Currently all releases are done through PyPI (`pip install cspyce`). The current version can be seen in the setup.py file, and also in the PyPI release history:

https://pypi.org/project/cspyce/#history

I added a tag called `v2.0.7` to the current commit. Please let me know what else we can do to be of service. You can contact me directly at `rfrench@seti.org`

**Comment by gpdf** [comment]
Thank you very much for the quick reply and action!
