### ISSUE TITLE
Introspection not available in IDEs

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/pds-cspyce#22]
Due to the way cspyce implements functions dynamically, introspection performed by IDEs such as VS Code doesn't work. This prevents function name completion, display of doc strings, etc.

**Comment by fyellin** [comment]
Attached are two versions of cspyce2.py, both generated.  Could you let me know if either or both of these solves your issues in VS Code. 

Both should be .py files, but github doesn't support uploading of that file type (why??) so I renamed them to .txt.

[cspyce2_large.txt](https://github.com/SETI/pds-cspyce/files/11604625/cspyce2_large.txt)
[cspyce2_small.txt](https://github.com/SETI/pds-cspyce/files/11604626/cspyce2_small.txt)

**Comment by rfrenchseti** [comment]
The small version auto-completes the argument list only. The large version does what I want - shows the arguments plus full doc string.
