### ISSUE TITLE
cspyce.dafus does not use array shape inputs nd, ni

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#39]
`cspyce.dafus` is supposed to return two arrays (one float, one int) of results of a chosen size, as specified by the second and third arguments `nd` and `ni`. The current results always return two arrays of size 256, regardless of the input. Here is a simplified unit test:

```
import cspyce as cs

spk = 'cspyce-unit-test-kernels/de405s_littleendian.bsp'
handle = cs.dafopr(spk)
cs.dafbfs(handle)
found = cs.daffna()
out = cs.dafgs()
dc, ic = cs.dafus(out, 2, 6)
assert len(dc) == 2
```

**Comment by rfrenchseti** [comment]
The problem appears to be in `cspyce0.i`, where the definition is:

```
%rename (dafus) dafus_c;
%apply (void RETURN_VOID) {void my_dafus_c};
%apply (ConstSpiceDouble IN_ARRAY1[ANY]) {ConstSpiceDouble sum[DAFSIZE]};
%apply (SpiceDouble     OUT_ARRAY1[ANY]) {SpiceDouble dc[DAFSIZE]};
%apply (SpiceInt        OUT_ARRAY1[ANY]) {SpiceInt ic[DAFSIZE]};
```

I don't see that this provides any way for the return arrays to be something other than 256 elements (`DAFSIZE`).

**Comment by fyellin** [comment]
cspice doesn't have typemaps that can handle this.  Assign this to me if you think it needs to be fixed.

**Comment by fyellin** [comment]
I'm also going to note.  In the example given, the result returned by
dafgs() is also an array of size 256.  Is that the correct result?  What
should determine the size of the returned array?

**Comment by esimpsons3ti** [comment]
It look slike dafgda() is the actual root of the problem. `spiceypy.dafgda()` returns an array with one value, which `cspyce.dafgda()` returns an array of [256] values. I apologize for the confusion.

**Comment by esimpsons3ti** [comment]
It also appears that `dafgs` has this same incorrect behavior. It is returning an array of 256 values instead of the expected 2. Here is a small test for `cspyce.dafgs:

```
import cspyce as cs
import numpy.testing as npt

spk = 'cspyce-unit-test-kernels/de405s_littleendian.bsp'

handle = cs.dafopr(spk)
cs.dafbfs(handle)
found = cs.daffna()
out = cs.dafgs()
npt.assert_array_almost_equal(
    out, [-9.46511378160646408796e07, 3.15662463183953464031e08]
)
```

**Comment by fyellin** [comment]
I'm going to need some help here.

When I look at https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/dafgs.html, I see in the sample code that they call 
              INTEGER               MAXSUM
              PARAMETER           ( MAXSUM = 125 )
              DOUBLE PRECISION      SUM( MAXSUM )
              .......
              CALL DAFGS ( SUM )

I don't see how they know to shrink SUM down to 2 elements, or where this "2" comes from.  Any idea?

**Comment by fyellin** [comment]
The spiceypy [implementation](https://github.com/AndrewAnnex/SpiceyPy/blob/main/src/spiceypy/spiceypy.py) seems to have the same behavior for dafgs that we do, except it uses 125.  You can pass it a numeric argument, and it will shrink the array down to that size.  But the user specifies the size.  Much like the ni/nd arguments of dafus.

Lemme know what you want me to do.  I can certainly add a size argument.

**Comment by rfrenchseti** [comment]
According to https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/daf.html, there are 125 values in a summary array.

I don't see any way to figure out what the proper size should be. I think it really is supposed to be 125 values, even though some may be unused. The better question then is why `spiceypy` allows you to shrink it in the first place.

**Comment by fyellin** [comment]
In cspyce_typemaps.i, we have

#define DAFSIZE 256     // DAF size

Is that a mistake?  Should it have been 125 all along?

**Comment by rfrenchseti** [comment]
I don't think it's that simple. DAFSIZE is used for different purposes. Any place it returns a "summary" the maximum size is 125. This includes: dafgs, dafgsr, and dafps. In other cases, it's used to return all of the values in the actual array between two endpoints. This includes dafgda, dafus, and dafgsr. In these cases, I see no limit on the amount of data that can be returned, but it can always be deduced from the arguments to the function. I think it we limit these functions to 125, or 256, or any finite number, we will be preventing the full use of the function.

**Comment by fyellin** [comment]
Okay.  I'm going go create a new variable DAF_SUMMARY_SIZE = 125

dafus and dafgda continue to use DAFSIZE.
dafgs uses DAFSUMMARYSIZE

We don't implement any of the others. 

(You included dafgsr in both lists, so I'm not sure what's going on there.  But we don't implement it, so I don't care yet.)

**Comment by rfrenchseti** [comment]
I don’t think that solves the problem that DAFSIZE is still the wrong way to implement it. The return size should be derived from the begin and end parameters.

**Comment by fyellin** [comment]
Reimplemented without DAFSIZE. S and

**Comment by fyellin** [comment]
Fixed.
