### ISSUE TITLE
cspyce.dp2hx() requires additional argument it does not need

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#52]
The function `dp2hx()` converts floating-point numbers to their base-16 scientific notation counterparts. The resulting output `hxstr` is given as a string. Here is an example of the expected functionality:

```
>>> x = cs.dp2hx(1.0)
>>> print(x)

"1^1"
```
Currently the function is failing, returning this error:

```
E   TypeError: dp2hx() missing 1 required positional argument: 'hxstr'
```

This function should not need another input argument to work, but it is asking for one. This argument also shares the name of its expected output result. Here is a small unit test:

```
def test_dp2hx():
    assert cs.dp2hx(2.0e-9) == "89705F4136B4A8^-7"
    assert cs.dp2hx(1.0) == "1^1"
    assert cs.dp2hx(-1.0) == "-1^1"
    assert cs.dp2hx(1024.0) == "4^3"
```

**Comment by fyellin** [comment]
This should be fixed.  Emilie should close this once the test has been added.

**Comment by esimpsons3ti** [comment]
This is now fixed. Closing issue.
