### ISSUE TITLE
Should some CSPICE functions be written in Python?

### ISSUE THREAD

**Issue by fyellin** [SETI/pds-cspyce#76]
There are a few CSPICE functions that are just "numeric" functions.  These are functions that do things like.

- Add and subtract arrays
- Scale arrays
- Take the linear combination of two similarly shaped arrays
- Copy and negate arrays
- Matrix multiplication of various sorts
- Return π

There is no astronomy involved in any of these.  It would be simpler (and faster!) to just implement these in Python and discard the SWIG code.  We would of course still have tests to insure that these are returning the same answers as the SWIG functions.

Anything that deletes SWIG code and C code is a win as far as I'm concerned.  Are there arguments against this?

**Comment by rfrenchseti** [comment]
We decided the answer is...no.
