### ISSUE TITLE
`ekgd` does not give the correct `ddata` value

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/pds-cspyce#88]
The function `ekgd` returns an element of an entry in a column of floating-point type in a specified row of a SPICE Events Kernel (EK). Here are the inputs and returns:

```
    Inputs:
      int   selidx = Index of parent column in SELECT clause.
      int   row    = Row to fetch from.
      int   elment = Index of element, within column entry, to fetch.
    
    Returns:
      float ddata  = Double precision element of column entry.
      bool  null   = Flag indicating whether column entry was null.
    
    Note: Raise IndexError(INDEXOUTOFRANGE) if the column is not present
    in the row.
```

The unit test for this function is currently failing:

```
import cspyce as cs
import os
from gettestkernels import TEST_FILE_DIR


def cleanup_kernel(path):
    cs.kclear()
    cs.reset()
    if os.path.isfile(path):
        os.remove(path)  # pragma: no cover
    pass
    
ekpath = os.path.join(TEST_FILE_DIR, "example_ekgd.ek")
cleanup_kernel(ekpath)
handle = cs.ekopn(ekpath, ekpath, 0)
segno, rcptrs = cs.ekifld(
    handle,
    "test_table_ekgd",
    2,
    ["c1"],
    ["DATATYPE = DOUBLE PRECISION, NULLS_OK = TRUE"],
)
cs.ekacld(
    handle, segno, "c1", [1.0, 2.0], [1, 1], [False, False], rcptrs
)
cs.ekffld(handle, segno, rcptrs)
cs.ekcls(handle)
cs.kclear()
cs.furnsh(ekpath)
nmrows = cs.ekfind("SELECT C1 FROM TEST_TABLE_EKGD")
d, null = cs.ekgd(0, 0, 0)
assert not null
assert d == 1.0
d, null = cs.ekgd(0, 1, 0)
assert not null
assert d == 2.0
cs.kclear()
cleanup_kernel(ekpath)
assert not os.path.exists(ekpath)
```

The failure occurs on the first assert for the `ddata` value (represented here as `d`). `d` should pass this assert, but it is instead giving a value of `4.2439915824e-314`. This value has the correct data type, but is otherwise incorrect.

**Comment by fyellin** [comment]
I see a call to ekifld.  Has that been fixed already?

**Comment by fyellin** [comment]
Bug is in ekacld.  cspyce0_part2.i,  4433ff.  

```
%apply (ConstSpiceInt  IN_ARRAY1[]) {ConstSpiceDouble  dvals[]};
```

should be 

```
%apply (ConstSpiceDouble  IN_ARRAY1[]) {ConstSpiceDouble  dvals[]};
```

**Comment by rfrenchseti** [comment]
The pull referenced above is not passing the test suite.

**Comment by esimpsons3ti** [comment]
Yes, but it’s now due to test_kernels.py, a file that predates my work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rfrenchseti** [comment]
True, but doesn't matter. I can't merge a pull with failing tests. You need to fix `test_kernels.py` now that the function is returning the correct value.

**Comment by esimpsons3ti** [comment]
The pull request is now passing.

From: Robert French ***@***.***>
Date: Monday, June 12, 2023 at 6:39 PM
To: SETI/pds-cspyce ***@***.***>
Cc: Emilie Simpson ***@***.***>, Assign ***@***.***>
Subject: Re: [SETI/pds-cspyce] `ekgd` does not give the correct `ddata` value (Issue #88)

True, but doesn't matter. I can't merge a pull with failing tests. You need to fix test_kernels.py now that the function is returning the correct value.
